### ISSUE TITLE
PR comment says 6 failed tests but only one actually failed

### ISSUE THREAD

**Issue by ceceliacreates** [RecordReplay/action-playwright#10]
The text in the comment says we've uploaded replays of 6 failed tests, but only one actually fails. We are also uploading the passes which is why there are 6. Not sure if we can clarify in the comment how many actually failed, otherwise we may just want to say we uploaded `n` replays.

<img width="859" alt="Screen Shot 2022-06-17 at 11 41 46 AM" src="https://user-images.githubusercontent.com/40367173/174332101-c37a5f17-8ddf-4106-8ff3-996fab56c6a3.png">

**Comment by jaril** [comment]
This is fixed now!
