### ISSUE TITLE
Update branding of failed test comment

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/action-playwright#4]
We can do better than this :)

<img width="785" alt="image" src="https://user-images.githubusercontent.com/788456/159025808-21de7b3d-4a9a-4569-9ef1-e06e35697635.png">

Noting that the displayed title is generated in the action from the status and the test title. The "[FAILED]" is handy for displaying in replay but is redundant when rendered under a "Failed Tests" header.

**Comment by ryanjduffy** [comment]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/788456/165193570-631dce0b-25b6-4f52-945f-7147032ee1b0.png">

**Comment by ryanjduffy** [comment]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/788456/165195134-e81263b5-30d7-4a18-82b2-331f01790a49.png">

**Comment by ryanjduffy** [comment]
Added support for a "source" arg as well so a little more context can be added if you're running the same test suite multiple times (e.g once per platform)

<img width="738" alt="image" src="https://user-images.githubusercontent.com/788456/165378127-858fdff8-16d2-4057-b6ed-0754a82f6fa9.png">

**Comment by jonbell-lot23** [comment]
Looking good @ryanjduffy !
